[application]
name = "probex-viewer"
default_platform = "fullstack"

[web.app]
title = "Probex Trace Viewer"

[web.watcher]
reload_html = true
watch_path = ["src", "assets", "tailwind.css"]

[web.resource]
style = []
script = [
  "https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js",
  "https://cdn.jsdelivr.net/npm/echarts-gl@2.0.9/dist/echarts-gl.min.js",
]

[web.resource.dev]
style = []
script = [
  "https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js",
  "https://cdn.jsdelivr.net/npm/echarts-gl@2.0.9/dist/echarts-gl.min.js",
]

[web.resource.release]
style = []
script = []
